name: Durex Sign

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 北京时间每天8点自动运行

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run sign.py
        env:
          DLS: ${{ secrets.DLS }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
        run: python sign.py
